name: Palki Local
values:
  - key: baseUrl
    value: 'http://localhost:3001/api/v1'
  - key: token
    value: ''
  - key: adminToken
    value: ''
  - key: refreshToken
    value: ''
  - key: userId
    value: ''
  - key: paymentId
    value: ''
  - key: agentId
    value: ''
  - key: matchId
    value: ''
  - key: postSlug
    value: ''
  - key: mediaId
    value: ''
color: 120
