ALTER TABLE agents ADD COLUMN IF NOT EXISTS "commissionPercent" DECIMAL DEFAULT 10.0;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS "totalEarnings" DECIMAL DEFAULT 0;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS "successfulMatches" INTEGER DEFAULT 0;
